### PR TITLE
Added short datestamp YYMMDD.

### PR DESCRIPTION
**Pull request by rrottmann**
Added a short datestamp format YYMMDD that uses only 2 digits for the year.

### CODE REVIEW

**Review by novoid — CHANGES_REQUESTED** [review]
I assume there is something going on with this commit. There are too many files which do not belong to this commit.

**Comment by novoid** [comment]
Hm, I can see where this is coming from. However, since I will not use this format myself, I tend to add it with the "untested" attribute. I have too many tools using date-stamps I would need to extend.

**Comment by nbehrnd** [comment]
@rrottmann On the way completing tests about date2name's action *on files* with Linux Debian (cf. [here](https://github.com/novoid/date2name/pull/14)), I recognized the short format suggested by you (YYMMDD) already was implemented into the program's functionality.

Based on this observation, what do you think about a two-step suggestion; namely
+ closing *this* pull request (because prepending YYMMDD apparently works), .and.
+ opening a separate pull request about the other feature suggested by you, i.e. executables of date2name for Windows?

**Comment by novoid** [comment]
Yes, I would prefer to split up this pull request to single features. If you are unsure or do have questions to discuss, please do contact me.

**Pull request closed without merging**
